(******************************************************************************)
(*                                                                            *)
(*             Rice's Theorem for Bounded-Memory Reactive Systems             *)
(*                                                                            *)
(*     Specialization of Rice's theorem to semantic classification of         *)
(*     behavior in bounded reactive systems. Separate time-bounded            *)
(*     lemma: semi-decidability within k cycles is impossible.                *)
(*     Reduction from the bounded halting problem.                            *)
(*                                                                            *)
(*     "The limits of my language mean the limits of my world."               *)
(*     – Ludwig Wittgenstein, 1922                                            *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: March 20, 2026                                                   *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
